-- MySQL Script generated by MySQL Workbench
-- Tue Mar 16 22:57:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_nome_minha_casa_mais_bonita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_nome_minha_casa_mais_bonita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_nome_minha_casa_mais_bonita` DEFAULT CHARACTER SET utf8 ;
USE `db_nome_minha_casa_mais_bonita` ;

-- -----------------------------------------------------
-- Table `db_nome_minha_casa_mais_bonita`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nome_minha_casa_mais_bonita`.`tb_categoria` (
  `id_tb_categoria` INT NOT NULL AUTO_INCREMENT,
  `classes` VARCHAR(20) NOT NULL,
  `descrisao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tb_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nome_minha_casa_mais_bonita`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nome_minha_casa_mais_bonita`.`tb_usuario` (
  `id_tb_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tb_usuario`),
  UNIQUE INDEX `id_tb_usuario_UNIQUE` (`id_tb_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_nome_minha_casa_mais_bonita`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_nome_minha_casa_mais_bonita`.`tb_produto` (
  `id_tb_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `quantidade` MEDIUMINT(20) NOT NULL,
  `valor` VARCHAR(20) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `id_tb_categoria` INT NOT NULL,
  `id_tb_usuario` INT NOT NULL,
  PRIMARY KEY (`id_tb_produto`),
  UNIQUE INDEX `idtb_produto_UNIQUE` (`id_tb_produto` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categoria_idx` (`id_tb_categoria` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_usuario1_idx` (`id_tb_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_categoria`
    FOREIGN KEY (`id_tb_categoria`)
    REFERENCES `db_nome_minha_casa_mais_bonita`.`tb_categoria` (`id_tb_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_usuario1`
    FOREIGN KEY (`id_tb_usuario`)
    REFERENCES `db_nome_minha_casa_mais_bonita`.`tb_usuario` (`id_tb_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
